name: Java CI with Gradle

# Workflow sẽ chạy khi có push lene nhánh 'main' hoặc pull request
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    # Chạy workflow trên môi trường Ubuntu mới nhất
    runs-on: ubuntu-latest

    steps:
      # Bước 1: Checkout code từ repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Bước 2: Thiết lập JDK cho Java
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # hoặc 'zulu' tùy vào nhu cầu của bạn
          java-version: '17'

      # Bước 3: Caching Gradle dependencies để tăng tốc độ build
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Bước 4: Kiểm tra phiên bản Gradle wrapper
      - name: Verify Gradle Wrapper
        run: ./gradlew wrapper --gradle-version

      # Bước 5: Build dự án với Gradle
      - name: Build with Gradle
        run: ./gradlew build --no-daemon

      # Bước 6: Chạy kiểm thử
      - name: Run tests
        run: ./gradlew test --no-daemon

      # Bước 7: Lưu trữ các báo cáo kiểm thử (test reports) nếu cần
      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: build/reports/tests/test # Đường dẫn tới test report của Gradle

      # Bước 8: Lưu trữ file build output (nếu cần)
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: build/libs # Đường dẫn tới file output build (thường là file .jar)
